struct	tsw	t[] = {
	"kernel",	STACK,	NULL,
	"k",		STACK,	NULL,
	"stack",	STACK,	"kernel stack",
	"s",		STACK,	NULL,
	"trace",	TRACE,	"kernel stack trace",
	"trace -",	TRACE,	"trace using saved r5",
	"r5",		R5,	"r5 for stack trace start",
	"call",		TRACE,	NULL,
	"t",		TRACE,	NULL,
	"u",		UAREA,	"user area",
	"user",		UAREA,	NULL,
	"u_area",	UAREA,	NULL,
	"uarea",	UAREA,	NULL,
	"ka6",		KA6,	"user area segmentation register",
	"proc",		PROC,	"process table",
	"proc -r",	PROC,	"runnable processes",
	"p",		PROC,	NULL,
	"file",		FILES,	"file table",
	"f",		FILES,	NULL,
	"inode",	INODE,	"inode table",
	"inode -",	INODE,	"inode table with block addresses",
	"i",		INODE,	NULL,
	"mount",	MOUNT,	"mount table",
	"m",		MOUNT,	NULL,
	"text",		TEXT,	"text table",
	"x",		TEXT,	NULL,
	"tty",		TTY,	"tty structures",
	"stat",		STAT,	"dump statistics",
	"var",		VAR,	"system variables",
	"v",		VAR,	NULL,
	"buf",		BUFHDR,	"buffer headers",
	"bufhdr",	BUFHDR,	NULL,
	"buffer",	BUFFER,	"buffer data",
	"b",		BUFFER,	NULL,
	"?",		Q,	NULL,
	"callout",	TOUT,	"callout table",
	"time",		TOUT,	NULL,
	"tout",		TOUT,	NULL,
	"timeout",	TOUT,	NULL,
	"ts",		TNS,	"text address namelist search",
	"ds",		DS,	"data address namelist search",
	"nm",		NM,	"name search",
	"od",		OD,	"dump symbol values",
	"map",		MAP,	"map structures",
	"!",		Q,	"escape to shell",
	"q",		QUIT,	"exit",
	"quit",		QUIT,	NULL,
	NULL,		NULL,	NULL
};

struct	prmode	prm[] = {
	"decimal",	DECIMAL,
	"dec",		DECIMAL,
	"e",		DECIMAL,
	"octal",	OCTAL,
	"oct",		OCTAL,
	"o",		OCTAL,
	"directory",	DIRECT,
	"direct",	DIRECT,
	"dir",		DIRECT,
	"d",		DIRECT,
	"write",	WRITE,
	"w",		WRITE,
	"character",	CHAR,
	"char",		CHAR,
	"c",		CHAR,
	"inode",	INODE,
	"i",		INODE,
	"byte",		BYTE,
	"b",		BYTE,
	"hex",		HEX,
	"h",		HEX,
	NULL,		NULL
} ;
