#define AUTOINDENT      0
#define AUTOPRINT       1
#define AUTOWRITE       2
#define BEAUTIFY        3
#define DIRECTORY       4
#define ERRORBELLS      5
#define HARDTABS        6
#define IGNORECASE      7
#define LISP            8
#define LIST            9
#define MAGIC           10
#define NUMBER          11
#define OPEN            12
#define OPTIMIZE        13
#define PARAGRAPHS      14
#define PROMPT          15
#define READONLY        16
#define REDRAW          17
#define REPORT          18
#define SCROLL          19
#define SECTIONS        20
#define SHELL           21
#define SHIFTWIDTH      22
#define SHOWMATCH       23
#define SLOWOPEN        24
#define TABSTOP         25
#define TAGLENGTH       26
#define TTYTYPE         27
#define TERM            28
#define TERSE           29
#define WARN            30
#define WINDOW          31
#define WRAPSCAN        32
#define WRAPMARGIN      33
#define WRITEANY        34

#define	NOPTS	35
