
/* entries.decs */
 
/* constants giving the number of opcode table entries for each instruction */
 
#define	ADCENT		1
#define	ADCBENT		1
#define	ADDENT		5
#define	ADDBENT		5
#define	ADDLENT		5
#define	ANDENT		5
#define	ANDBENT		5
#define	BITENT		5
#define	BITBENT		5
#define	CALLENT		3
#define	CALRENT		1
#define	CLRENT		4
#define	CLRBENT		4
#define	COMENT		4
#define	COMBENT		4
#define	COMFLGENT	4
#define	CPENT		8
#define	CPBENT		8
#define	CPLENT		5
#define	CPDENT		1
#define	CPDBENT		1
#define	CPDRENT		1
#define	CPDRBENT	1
#define	CPIENT		1
#define	CPIBENT		1
#define	CPIRENT		1
#define	CPIRBENT	1
#define	CPSDENT		1
#define	CPSDBENT	1
#define	CPSDRENT	1
#define	CPSDRBENT	1
#define	CPSIENT		1
#define	CPSIBENT	1
#define	CPSIRENT	1
#define	CPSIRBENT	1
#define	DABENT		1
#define	DECENT		8
#define	DECBENT		8
#define	DIENT		2
#define	DIVENT		5
#define	DIVLENT		5
#define	DJNZENT		1
#define	DBJNZENT	1
#define	EIENT		2
#define	EXENT		4
#define	EXBENT		4
#define	EXTSENT		1
#define	EXTSBENT	1
#define	EXTSLENT	1
#define FADDDENT	1
#define FADDFENT	1
#define FCPDENT		1
#define FCPFENT		1
#define FDIVDENT	1
#define FDIVFENT	1
#define FDTODENT	1
#define FDTOFENT	1
#define FDTOIENT	1
#define FDTOLENT	1
#define FFTODENT	1
#define FFTOFENT	1
#define FFTOIENT	1
#define FFTOLENT	1
#define FITODENT	1
#define FITOFENT	1
#define FITOIENT	1
#define FITOLENT	1
#define FLTODENT	1
#define FLTOFENT	1
#define FLTOIENT	1
#define FLTOLENT	1
#define FMULDENT	1
#define FMULFENT	1
#define FNEGDENT	1
#define FNEGFENT	1
#define FSUBDENT	1
#define FSUBFENT	1
#define	HALTENT		1
#define	INENT		2
#define	INBENT		2
#define	INCENT		8
#define	INCBENT		8
#define	INDENT		1
#define	INDBENT		1
#define	INDRENT		1
#define	INDRBENT	1
#define	INIENT		1
#define	INIBENT		1
#define	INIRENT		1
#define	INIRBENT	1
#define	IRETENT		1
#define	JPENT		6
#define JPRENT		6
#define	JRENT		2
#define	LDENT		15
#define	LDBENT		15
#define	LDLENT		12
#define	LDAENT		4
#define	LDARENT		1
#define	LDCTLENT	2
#define	LDCTLBENT	2
#define	LDDENT		1
#define	LDDBENT		1
#define	LDDRENT		1
#define	LDDRBENT	1
#define	LDIENT		1
#define	LDIBENT		1
#define	LDIRENT		1
#define	LDIRBENT	1
#define	LDKENT		1
#define	LDMENT		6
#define	LDPSENT		3
#define	LDRENT		2
#define	LDRBENT		2
#define	LDRLENT		2
#define	MBITENT		1
#define	MREQENT		1
#define	MRESENT		1
#define	MSETENT		1
#define	MULTENT		5
#define	MULTLENT	5
#define	NEGENT		4
#define	NEGBENT		4
#define	NOPENT		1
#define	ORENT		5
#define	ORBENT		5
#define	OTDRENT		1
#define	OTDRBENT	1
#define	OTIRENT		1
#define	OTIRBENT	1
#define	OUTENT		2
#define	OUTBENT		2
#define	OUTDENT		1
#define	OUTDBENT	1
#define	OUTIENT		1
#define	OUTIBENT	1
#define	POPENT		4
#define	POPLENT		4
#define	PUSHENT		5
#define	PUSHLENT	4
#define	RESENT		5
#define	RESBENT		5
#define	RESFLGENT	4
#define	RETENT		2
#define	RLENT		2
#define	RLBENT		2
#define	RLCENT		2
#define	RLCBENT		2
#define	RLDBENT		1
#define	RRENT		2
#define	RRBENT		2
#define	RRCENT		2
#define	RRCBENT		2
#define	RRDBENT		1
#define	SBCENT		1
#define	SBCBENT		1
#define	SCENT		1
#define	SDAENT		1
#define	SDABENT		1
#define	SDALENT		1
#define	SDLENT		1
#define	SDLBENT		1
#define	SDLLENT		1
#define	SETENT		5
#define	SETBENT		5
#define	SETFLGENT	4
#define	SINENT		1
#define	SINBENT		1
#define	SINDENT		1
#define	SINDBENT	1
#define	SINDRENT	1
#define	SINDRBENT	1
#define	SINIENT		1
#define	SINIBENT	1
#define	SINIRENT	1
#define	SINIRBENT	1
#define	SLAENT		2
#define	SLABENT		2
#define	SLALENT		2
#define	SLLENT		2
#define	SLLBENT		2
#define	SLLLENT		2
#define	SOUTENT		1
#define	SOUTBENT	1
#define	SOUTDENT	1
#define	SOUTDBENT	1
#define	SOTDRENT	1
#define	SOTDRBENT	1
#define	SOUTIENT	1
#define	SOUTIBENT	1
#define	SOTIRENT	1
#define	SOTIRBENT	1
#define	SRAENT		2
#define	SRABENT		2
#define	SRALENT		2
#define	SRLENT		2
#define	SRLBENT		2
#define	SRLLENT		2
#define	SUBENT		5
#define	SUBBENT		5
#define	SUBLENT		5
#define	TCCENT		1
#define	TCCBENT		1
#define	TESTENT		4
#define	TESTBENT	4
#define	TESTLENT	4
#define	TRDBENT		1
#define	TRDRBENT	1
#define	TRIBENT		1
#define	TRIRBENT	1
#define	TRTDBENT	1
#define	TRTDRBENT	1
#define	TRTIBENT	1
#define	TRTIRBENT	1
#define	TSETENT		4
#define	TSETBENT	4
#define	XORENT		5
#define	XORBENT		5

