/*
 * This file was generated by the mkbuiltins program.
 */

#define BLTINCMD 0
#define BREAKCMD 1
#define CATFCMD 2
#define CDCMD 3
#define DOTCMD 4
#define ECHOCMD 5
#define EVALCMD 6
#define EXECCMD 7
#define EXITCMD 8
#define EXPORTCMD 9
#define EXPRCMD 10
#define GETOPTSCMD 11
#define HASHCMD 12
#define JOBIDCMD 13
#define JOBSCMD 14
#define LCCMD 15
#define LINECMD 16
#define LOCALCMD 17
#define NLECHOCMD 18
#define PWDCMD 19
#define READCMD 20
#define RETURNCMD 21
#define SETCMD 22
#define SETVARCMD 23
#define SHIFTCMD 24
#define TRAPCMD 25
#define TRUECMD 26
#define UMASKCMD 27
#define UNSETCMD 28
#define WAITCMD 29

struct builtincmd {
      char *name;
      int code;
};

extern int (*const builtinfunc[])();
extern const struct builtincmd builtincmd[];
