/*
 * This file was generated by the mkbuiltins program.
 */

#include "shell.h"
#include "builtins.h"

int bltincmd();
int breakcmd();
int catfcmd();
int cdcmd();
int dotcmd();
int echocmd();
int evalcmd();
int execcmd();
int exitcmd();
int exportcmd();
int exprcmd();
int getoptscmd();
int hashcmd();
int jobidcmd();
int jobscmd();
int lccmd();
int linecmd();
int localcmd();
int nlechocmd();
int pwdcmd();
int readcmd();
int returncmd();
int setcmd();
int setvarcmd();
int shiftcmd();
int trapcmd();
int truecmd();
int umaskcmd();
int unsetcmd();
int waitcmd();

int (*const builtinfunc[])() = {
	bltincmd,
	breakcmd,
	catfcmd,
	cdcmd,
	dotcmd,
	echocmd,
	evalcmd,
	execcmd,
	exitcmd,
	exportcmd,
	exprcmd,
	getoptscmd,
	hashcmd,
	jobidcmd,
	jobscmd,
	lccmd,
	linecmd,
	localcmd,
	nlechocmd,
	pwdcmd,
	readcmd,
	returncmd,
	setcmd,
	setvarcmd,
	shiftcmd,
	trapcmd,
	truecmd,
	umaskcmd,
	unsetcmd,
	waitcmd,
};

const struct builtincmd builtincmd[] = {
	"bltin", 0,
	"break", 1,
	"continue", 1,
	"catf", 2,
	"cd", 3,
	".", 4,
	"echo", 5,
	"eval", 6,
	"exec", 7,
	"exit", 8,
	"export", 9,
	"readonly", 9,
	"expr", 10,
	"test", 10,
	"[", 10,
	"getopts", 11,
	"hash", 12,
	"jobid", 13,
	"jobs", 14,
	"lc", 15,
	"line", 16,
	"local", 17,
	"nlecho", 18,
	"pwd", 19,
	"read", 20,
	"return", 21,
	"set", 22,
	"setvar", 23,
	"shift", 24,
	"trap", 25,
	":", 26,
	"true", 26,
	"umask", 27,
	"unset", 28,
	"wait", 29,
	NULL, 0
};
