/*
 * This file was generated by the mksignames program.
 */

#include "shell.h"

char *const sigmesg[32] = {
      0,
      "Hangup",
      "Interrupt",
      "Quit",
      "Illegal instruction",
      "Trace/BPT trap",
      "abort",
      "EMT trap",
      "Floating exception",
      "Killed",
      "Bus error",
      "Memory fault",
      "Bad system call",
      "Broken pipe",
      "Alarm call",
      "Terminated",
      0,
      "Stopped",
      "Stopped",
      0,
      0,
      "Stopped (input)",
      "Stopped (output)",
      0,
      "Time limit exceeded",
      0,
      0,
      "Profiling alarm",
      0,
      0,
      "User signal 1",
      "User signal 2",
};
