/*	Plexus - Sys3 - August 1982	*/

static char table_c[] = "@(#)table.c	1.1";

# include "mfile2"

# include "myinc.h"

# define AWD SNAME|SOREG|SCON|STARREG|STAREG
# define RWD STAREG|SAREG


struct optab  table[] = {

ASSIGN,	INTAREG|FOREFF,
	SAREG|AWD,	TPOINT|TINT|TUNSIGNED|TCHAR|TUCHAR,
	SZERO,	TANY,
		0,	RRIGHT|RLEFT,
		"/*1*/	clrZB	AL#)\n",

ASSIGN,	INTAREG|FOREFF,
	SAREG|AWD,	TPOINT|TINT|TUNSIGNED|TCHAR|TUCHAR|TLONG|TULONG,
	RWD,	TFIT,
		0,	RLEFT|RRIGHT,
		"/*4*/	ldZB	AL,AR#)\n",

ASSIGN,	INTAREG|FOREFF,
	SAREG|AWD,	TPOINT|TINT|TUNSIGNED|TCHAR|TUCHAR,
	SCON,	TANY,
		0,	RLEFT|RRIGHT,
		"/*4+*/	ldZB	AL,AR#)\n",

ASSIGN,	INTAREG|FOREFF,
	RWD,	TPOINT|TINT|TUNSIGNED|TCHAR|TUCHAR|TLONG|TULONG,
	AWD|SAREG,	TFIT,
		0,	RLEFT|RRIGHT,
		"/*5*/	ldZB	AL,AR#)\n",

ASSIGN,	INTAREG|FOREFF,
	AWD,	TLONG|TULONG,
	SZERO,	TANY,
		0,	RRIGHT|RLEFT,
		"/*10*/	clr	AL\n	clr	UL\n",

ASSIGN,	INAREG|INTAREG|FOREFF,
	AWD,	TDOUBLE,
	RWD,	TDOUBLE,
		0,	RRIGHT,
		"/*17*/	ldm	AL,AR,$4\n",

ASSIGN,	INAREG|INTAREG|FOREFF,
	AWD,	TFLOAT,
	RWD,	TFLOAT,
		0,	RRIGHT,
		"/*17+*/#f	ldl	DL,QR#)\n",

ASSIGN, INTAREG|FOREFF,
	SFLD,	TANY,
	SZERO,	TANY,
		NAREG,	RRIGHT,
		"/*22*/	ld	A1,AL\n	and	A1,$N\n	ld	AL,A1\n",

ASSIGN, INTAREG|FOREFF,
	SFLD,	TANY,
	SCON,	TANY,
		NAREG,	RRIGHT,
		"/*22+*/	ld	A1,AL\n	and	A1,$N\
			\n#$	or	A1,$(AR<<H)&M#)\
			\n	ld	AL,A1\n",

ASSIGN, INTAREG|FOREFF,
	SFLD,	TANY,
	STAREG,	TANY,
		NAREG,	RRIGHT,
		"/*23*/	push	*r15,AR\n	ld	A1,AL\n	sll	AR,$H\
			\n	and	AR,$M\n	and	A1,$N\
			\n	or	A1,AR\n	ld	AL,A1\
			\n	pop	AR,*r15\n",

ASSIGN, INTAREG|FOREFF,
	SFLD,	TANY,
	AWD|SAREG,	TANY,
		2*NAREG,	RRIGHT,
		"/*24*/	ld	U1,AL\n	ld	A1,AR\n	sll	A1,$H\
			\n	and	A1,$M\n	and	U1,$N\
			\n	or	U1,A1\n	ld	AL,U1\n",

/* put this here so UNARY MUL nodes match OPLTYPE when appropriate */
OPLTYPE,	FOREFF,
	SANY,	TANY,
	SNAME|SOREG|SCON|RWD,	TANY,
		0,	RRIGHT,

		"/*26-*/\n",   /* this entry throws away
				computations which don't do anything */

OPLTYPE,	INTAREG,
	SANY,	TANY,
	SZERO,	TINT|TUNSIGNED|TPOINT|TCHAR|TUCHAR,
		NAREG,	RESC1,
		"/*26*/	ldk	A1,$0\n",

OPLTYPE,	INTAREG,
	SANY,	TANY,
	SZERO,	TLONG|TULONG,
		NAREG,	RESC1,
		"/*27*/	ldk	A1,$0\n	ldk	U1,$0\n",

OPLTYPE,	INTAREG,
	SANY,	TANY,
	SANY,	TINT|TUNSIGNED|TPOINT|TCHAR|TUCHAR|TLONG|TULONG,
		SMUSTDO|NAREG|NASR,	RESC1,
		"/*28*/	ldZB	A1,AR#)\n",

OPLTYPE,	INTEMP,
	SANY,	TANY,
	RWD,	TINT|TUNSIGNED|TPOINT,
		NTEMP,	RESC1,
		"/*30*/	ld	A1,AR\n",

OPLTYPE,	INTEMP,
	SANY,	TANY,
	RWD,	TCHAR|TUCHAR,
		NTEMP,	RESC1,
		"/*30+*/#L	ldb	A1,AR#)\n",

OPLTYPE,	INTEMP,
	SANY,	TANY,
	SANY,	TINT|TUNSIGNED|TPOINT,
		NTEMP,	RESC1,
		"/*31*/	push	*r15,r7\n	ld	r7,AR\
			\n	ld	A1,r7\n	pop	r7,*r15\n",

OPLTYPE,	FORCC,
	SANY,	TANY,
	SANY,	TINT|TUNSIGNED|TPOINT|TCHAR|TUCHAR,
		0,	RESCC,
		"/*34*/	cpZB	AR,$0#)\n",

OPLTYPE,	FORARG,
	SANY,	TANY,
	RWD|SCON,	TINT|TUNSIGNED|TPOINT,
		0,	RNULL,
		"/*37-*/	Z2	*r15,AR\n",

OPLTYPE,	FORARG,
	SANY,	TANY,
	SANY,	TINT|TUNSIGNED|TPOINT,
		0,	RNULL,
		"/*37*/	push	*r15,AR\nZ-",

OPLTYPE,	FORARG,
	SANY,	TANY,
	RWD,	TCHAR,
		0,	RNULL,
		"/*38-*/	extsb	AR\n	Z2	*r15,AR\n",

OPLTYPE,	FORARG,
	SANY,	TANY,
	RWD,	TUCHAR,
		0,	RNULL,
		"/*39-*/#H	ldb	AR,$0#)\n	Z2	*r15,AR\n",

OPLTYPE,	FORARG,
	SANY,	TANY,
	SOREG|RWD,	TLONG|TULONG,
		0,	RNULL,
		"/*39*/	pushl	*r15,DR\nZ-Z-",

OPLTYPE,	INTAREG,
	SANY,	TANY,
/*does this generate bad code ? * ?? */
	SAREG|AWD,	TUCHAR,
		NAREG|NASR,	RESC1,
		"/*40*/#L	ldb	A1,AR#)\n#H	ldb	A1,$0#)\n",

OPLTYPE,	INTAREG|INAREG,
	SANY,	TANY,
	AWD,	TLONG|TULONG,
		SMUSTDO|NAREG|NASR,	RESC1,
		"/*41*/	ldl	D1,DR\n",

/* what is 42 for??? */
OPLTYPE,	INTAREG|INAREG,  /* for use when there are no free regs */
	SANY,	TANY,
	AWD,	TLONG|TULONG,
		NAREG|NASR,	RESC1,
		"/*42*/	push	*r15,AR\n	ld	A1,UR\
			\n	pop	AR,*R15\n",

/* 43 will only put registers into temps ??? */
OPLTYPE,	INTEMP,
	SANY,	TANY,
	RWD,	TLONG|TULONG,
		2*NTEMP,	RESC1,
		"/*43*/	ldl	D1,DR\n",

OPLTYPE,	FORCC,
	SANY,	TANY,
	RWD,	TLONG|TULONG,
		NAREG,	RESCC,
		"/*44*/	cpl	DR,$0\n",

#ifdef shit
OPLTYPE, FORARG,
	SANY,	TANY,
	SCON,	TLONG|TULONG,
		0,	RNULL,
		"/*45*/		push	*r15,UR\nZ-	push	*r15,AR\nZ-",
#endif

OPLTYPE, FORARG,
	SANY,	TANY,
	SNAME|SOREG|STAREG|STARREG,	TLONG|TULONG,
		0,	RNULL,
		"/*46*/	pushl	*r15,DR\nZ-Z-",

OPLTYPE, FORARG,
	SANY,	TANY,
	AWD,	TDOUBLE,
		0,	RNULL,
		"/*47*/	pushl	*r15,ERZ-Z-\n	pushl	*r15,DRZ-Z-\n",

OPLTYPE, FORARG,
	SANY,	TANY,
	RWD,	TFLOAT,
		0,	RNULL,
		"/*47+*/	fftod	QR,ER\
			\n	pushl	*r15,ERZ-Z-\n	pushl	*r15,DRZ-Z-\n",

/*48 looks funny,why is sharing on? the first load could wipe out the pointer*/
OPLTYPE,	INTAREG|INAREG,
	SANY,	TANY,
	RWD,	TDOUBLE,
		NAREG|NASR,	RESC1,
		"/*48*/	ldl	D1,DR\n	ldl	E1,ER\n",

OPLTYPE,	INTAREG|INAREG,
	SANY,	TANY,
	AWD,	TDOUBLE,
		NAREG|NASR,	RESC1,
		"/*49*/	ldm	A1,AR,$4\n",

OPLTYPE,	INTEMP,
	SANY,	TANY,
	RWD,	TDOUBLE,
		4*NTEMP,	RESC1,
		"/*50*/	ldm	A1,AR,$4\n",

OPLTYPE,	INTEMP,
	SANY,	TANY,
	RWD,	TFLOAT,
		2*NTEMP,	RESC1,
		"/*50+*/	ldl	A1,ER\n",

OPLTYPE,	FORCC,
	SANY,	TANY,
	RWD,	TDOUBLE|TFLOAT,
		NAREG,	RESCC,
		"/*51*/	ldk	V1,$0\n	fitod	Q1,V1\n	fcp#d	QR,Q1#)\n",

OPLTYPE,	INTAREG|INAREG,
	SANY,	TANY,
	RWD,	TFLOAT,
		NAREG|NASR,	RESC1,
		"/*52*/		ldl	E1,ER\n",

OPLTYPE,	INTAREG|INAREG,
	SANY,	TANY,
	AWD,	TFLOAT,
		NAREG|NASR,	RESC1,
		"/*53*/	ldl	E1,DR\n",

OPLOG,	FORCC,
	SNAME|SCON,	TPOINT|TINT|TUNSIGNED,
	SCON,	TPOINT|TINT|TUNSIGNED,
		NAREG,	RESCC,
		"/*55-*/	ld	A1,AL\n	cp	A1,AR\nZI",

OPLOG,	FORCC,
	SAREG|AWD,	TPOINT|TINT|TUNSIGNED,
	SCON,	TPOINT|TINT|TUNSIGNED,
		0,	RESCC,
		"/*55*/	cp	AL,AR\nZI",

OPLOG,	FORCC,
	AWD,	TCHAR,
	SCCON,	TANY,
		0,	RESCC,
		"/*55+*/#L	cpb	AL,AR#)\nZI",

OPLOG,	FORCC,
	AWD,	TUCHAR,
	SUCCON,	TANY,
		0,	RESCC,
		"/*55++*/#L	cpb	AL,AR\n#)ZI",

OPLOG,	FORCC,
	RWD,	TPOINT|TINT|TUNSIGNED,
	SAREG|AWD,	TPOINT|TINT|TUNSIGNED,
		0,	RESCC,
		"/*56*/	cp	AL,AR\nZI",

OPLOG,	FORCC,
	RWD,	TCHAR|TUCHAR,
	AWD,	TCHAR|TUCHAR,
		0,	RESCC,
		"/*56*/#L	cpb	AL,AR#)\nZI",

OPLOG,	FORCC,
	RWD,	TDOUBLE|TFLOAT,
	RWD,	TFIT,
		0,	RESCC,
		"/*58*/	fcp#d	QL,QR#)\nZI",

OPLOG,	FORCC,
	RWD,	TLONG|TULONG,
	AWD,	TLONG|TULONG,
		0,	RESCC,
		"/*59*/	cpl	DL,DR\nZI",

CCODES,	INAREG|INTAREG,
	SANY,	TANY,
	SANY,	TINT|TUNSIGNED|TPOINT|TCHAR|TUCHAR,
		NAREG,	RESC1,
		"/*64*/ZN",

UNARY MINUS,	INAREG|INTAREG,
	STAREG,	TINT|TUNSIGNED|TCHAR|TUCHAR,
	SANY,	TANY,
		0,	RLEFT,
		"/*66*/	negZB	AL#)\n",

UNARY MINUS,	INAREG|INTAREG,
	SAREG,	TINT|TUNSIGNED,
	SANY,	TANY,
		NAREG,	RESC1,
		"/*67*/	ld	A1,AL\n	neg	A1\n",

UNARY MINUS,	INTAREG,
	RWD|AWD,	TLONG|TULONG,
	SANY,	TANY,
		NAREG,	RESC1,
		"/*68*/	ldk	A1,$0\n	ldk	U1,$0\n	subl	D1,DL\n",

UNARY MINUS,	INTAREG|INAREG,
	RWD,	TDOUBLE|TFLOAT,
	SANY,	TANY,
		0,	RLEFT,
		"/*69*/	fneg#d	QL#)\n",

COMPL,	INAREG|INTAREG,
	STAREG,	TINT|TUNSIGNED|TCHAR|TUCHAR,
	SANY,	TANY,
		0,	RLEFT,
		"/*70*/	comZB	AL#)\n",

COMPL,	INAREG|INTAREG,
	SAREG,	TINT|TUNSIGNED,
	SANY,	TANY,
		NAREG,	RESC1,
		"/*71*/	ld	A1,AL\n	com	A1\n",

INCR,	INTAREG|FOREFF,
	SAREG,	TCHAR|TUCHAR,
	SCON,	TANY,
		NAREG,	RESC1,
		"F/*73*/	ldZB	A1,AL#)\
			\n/*73+*/	addZB	AL,AR#)\n",

DECR,	INTAREG|FOREFF,
	SAREG,	TINT|TUNSIGNED|TPOINT|TCHAR|TUCHAR,
	SSCON,	TANY,
		NAREG,	RESC1,
		"F/*74*/	ldZB	A1,AL#)\
			\n/*74+*/	decZB	AL,AR#)\n",

DECR,	INTAREG|FOREFF,
	SAREG,	TINT|TUNSIGNED|TPOINT|TCHAR|TUCHAR,
	SCON,	TANY,
		NAREG,	RESC1,
		"F/*75*/	ldZB	A1,AL#)\
			\n/*75+*/	subZB	AL,AR#)\n",

INCR,	INAREG|INTAREG|FOREFF,
	AWD|SAREG,	TINT|TUNSIGNED|TPOINT|TCHAR|TUCHAR,
	SSCON,	TANY,
		NAREG,	RESC1,
		"F/*76*/	ldZB	A1,AL#)\
			\n/*76+*/	incZB	AL,AR#)\n",

INCR,	INAREG|INTAREG|FOREFF,
	AWD|SAREG,	TINT|TUNSIGNED|TPOINT,
	SCON,	TANY,
		2*NAREG,	RESC1,
		"F/*77*/	ld	A1,AL\n/*77+*/	ld	U1,AL\
			\n	add	U1,AR\n	ld	AL,U1\n",

DECR,	INAREG|INTAREG|FOREFF,
	AWD|SAREG,	TINT|TUNSIGNED|TPOINT|TCHAR|TUCHAR,
	SSCON,	TANY,
		NAREG,	RESC1,
		"F/*78*/	ldZB	A1,AL#)\
			\n/*78+*/	decZB	AL,AR#)\n",

DECR,	INAREG|INTAREG|FOREFF,
	AWD|SAREG,	TINT|TUNSIGNED|TPOINT,
	SCON,	TANY,
		2*NAREG,	RESC1,
		"F/*79*/	ld	A1,AL\n/*79+*/	ld	U1,AL\
			\n	sub	U1,AR\n	ld	AL,U1\n",

INCR,	INTAREG|FOREFF,
	RWD,	TLONG|TULONG,
	SCON,	TANY,
		NAREG,	RESC1,
		"F/*80*/	ldl	D1,DL\n/*80+*/	addl	DL,DR\n",

DECR,	INTAREG|FOREFF,
	RWD,	TLONG|TULONG,
	SCON,	TANY,
		NAREG,	RESC1,
		"F/*81*/	ldl	D1,DL\n/*81+*/	subl	DL,DR\n",

COMPL,	INTAREG,
	RWD,	TLONG|TULONG,
	SANY,	TANY,
		0,	RLEFT,
		"/*82*/	com	AL\n	com	UL\n",

AND,	FORCC,
	AWD|RWD,	TINT|TUNSIGNED|TPOINT|TCHAR|TUCHAR,
	SCONSET,	TANY,
		0,	RESCC,
		"/*83-*/	bitZB	AL,#S#)\n",

ASG MUL,	INTAREG,
	STAREG,	TINT|TUNSIGNED|TPOINT|TCHAR|TUCHAR,
	RWD|AWD,	TINT|TUNSIGNED|TPOINT,
		2*NAREG|NASL,	RESC1|RESCLIL,
		"/*88*/	ld	U1,AL\n	mult	D1,AR\n",

ASG MUL,	INTAREG,
	STAREG,	TLONG|TULONG,
	AWD|RWD,	TLONG|TULONG,
		2*NAREG|NASL,	RESC1|RESCLLQ,
		"/*89*/	ldl	E1,DL\n	multl	Q1,DR\n",

ASG DIV,	INTAREG,
	STAREG,	TINT|TUNSIGNED|TPOINT|TCHAR|TUCHAR,
	RWD|AWD,	TINT|TUNSIGNED|TPOINT,
		2*NAREG|NASL,	RESC1|RESCLIL,
		"/*90*/	ld	U1,AL\nZV	div	D1,AR\n",

ASG DIV,	INTAREG,
	STAREG,	TLONG|TULONG,
	AWD|RWD,	TLONG|TULONG,
		2*NAREG|NASL,	RESC1|RESCLLQ,
		"/*91*/	ldl	E1,DL\
			\nZV	divl	Q1,DR\n",

ASG MOD,	INTAREG,
	STAREG,	TINT|TPOINT|TUNSIGNED|TCHAR|TUCHAR,
	RWD|AWD,	TINT|TUNSIGNED|TPOINT,
		/*2*NAREG|NASL,	RLEFT|RESCUIL,*/
		2*NAREG|NASL,	RESC1,
		"/*92*/	ld	U1,AL\nZV	div	D1,AR\n",

ASG MOD,	INTAREG,
	STAREG,	TLONG|TULONG,
	AWD|RWD,	TLONG|TULONG,
		2*NAREG|NASL,	RESC1,
		"/*93*/	ldl	E1,DL\
			\nZV	divl	Q1,DR\n",

ASG PLUS,	INTAREG|FORCC,
	SAREG|AWD,	TINT|TUNSIGNED|TPOINT|TCHAR|TUCHAR,
	SSCON,	TINT,
		0,	RLEFT|RESCC,
		"/*94*/	incZB	AL,AR#)\n",

ASG PLUS,	INAREG|INTAREG|FORCC,
	RWD,	TINT|TUNSIGNED|TPOINT|TCHAR|TUCHAR|TLONG|TULONG,
	SAREG|AWD,	TFIT,
		0,	RLEFT|RESCC,
		"/*95*/	addZB	AL,AR#)\n",

ASG PLUS,	FOREFF,
	AWD,	TLONG|TULONG,
	SONE,	TFIT,
		0,	RLEFT,
		"/*96*/\tinc\tUL,UR\n\tjpr\tnz,#j\n\tinc\tAL,$1\n#l\n",

ASG MINUS,	INTAREG|FORCC,
	SAREG|AWD,	TINT|TUNSIGNED|TPOINT|TCHAR|TUCHAR,
	SSCON,	TINT,
		0,	RLEFT|RESCC,
		"/*97*/	decZB	AL,AR#)\n",

ASG MINUS,	INTAREG|FORCC,
	RWD,	TINT|TUNSIGNED|TPOINT|TCHAR|TUCHAR|TLONG|TULONG,
	SAREG|AWD,	TFIT,
		0,	RLEFT|RESCC,
		"/*98*/	subZB	AL,AR#)\n",

ASG OR,	INAREG|FOREFF,
	AWD|RWD,	TINT|TUNSIGNED|TPOINT|TCHAR|TUCHAR,
	SCONSET,	TANY,
		0,	RLEFT,
		"/*100-*/	setZB	AL,#S#)\n",

ASG OR, 	INTAREG|FORCC,
	RWD,	TINT|TUNSIGNED|TPOINT|TCHAR|TUCHAR,
	SAREG|AWD,	TFIT,
		0,	RLEFT|RESCC,
		"/*100*/	orZB	AL,AR#)\n",

ASG AND,	INAREG|FOREFF,
	AWD|RWD,	TINT|TUNSIGNED|TPOINT|TCHAR|TUCHAR,
	SCONRES,	TANY,
		0,	RLEFT,
		"/*102-*/	resZB	AL,#R#)\n",

ASG AND,	INTAREG|FORCC,
	RWD,	TINT|TUNSIGNED|TPOINT|TCHAR|TUCHAR,
	SAREG|AWD,	TFIT,
		0,	RLEFT|RESCC,
		"/*102*/	andZB	AL,AR#)\n",

ASG ER,	INTAREG|FORCC,
	RWD,	TINT|TUNSIGNED|TPOINT|TCHAR|TUCHAR,
	SAREG|AWD,	TFIT,
		0,	RLEFT|RESCC,
		"/*104*/	xorZB	AL,AR#)\n",

ASG LS, 	INTAREG,
	RWD,	TINT|TCHAR|TLONG,
	SCON,	TINT|TUNSIGNED|TPOINT,
		0,	RLEFT,
		"/*107--*/	slaZB	AL#),AR\n",

ASG LS, 	INTAREG,
	RWD,	TUNSIGNED|TPOINT|TUCHAR|TULONG,
	SCON,	TINT|TUNSIGNED|TPOINT,
		0,	RLEFT,
		"/*107-*/	sllZB	AL#),AR\n",

ASG LS, 	INTAREG,
	RWD,	TINT|TCHAR|TLONG,
	RWD,	TINT|TUNSIGNED|TPOINT,
		0,	RLEFT,
		"/*107*/	sdaZB	AL#),AR\n",

ASG LS, 	INTAREG,
	RWD,	TUNSIGNED|TPOINT|TUCHAR|TULONG,
	RWD,	TINT|TUNSIGNED|TPOINT,
		0,	RLEFT,
		"/*107+*/	sdlZB	AL#),AR\n",

ASG RS, 	INTAREG,
	RWD,	TINT|TCHAR|TLONG,
	SCON,	TANY,
		0,	RLEFT,
		"/*108*/	sraZB	AL#),AR\n",

ASG RS, 	INTAREG,
	RWD,	TUNSIGNED|TPOINT|TUCHAR|TULONG,
	SCON,	TANY,
		0,	RLEFT,
		"/*109*/	srlZB	AL#),AR\n",

ASG RS, 	INTAREG,
	RWD,	TINT|TCHAR|TLONG,
	STAREG,	TINT|TUNSIGNED|TPOINT,
		0,	RLEFT,
		"/*110*/	neg	AR\n	sdaZB	AL#),AR\n",

ASG RS, 	INTAREG,
	RWD,	TUNSIGNED|TPOINT|TUCHAR|TULONG,
	STAREG,	TINT|TUNSIGNED|TPOINT,
		0,	RLEFT,
		"/*111*/	neg	AR\n	sdlZB	AL#),AR\n",

ASG PLUS, 	INTAREG,
	RWD,	TLONG|TULONG,
	SICON,	TINT|TLONG|TULONG,
		0,	RLEFT,
		"/*115*/	addl	DL,UR\n",

ASG PLUS,	INTAREG,
	RWD,	TPOINT,
	AWD,	TLONG|TULONG,
		0,	RLEFT,
		"/*118*/	add	AL,UR\n",

ASG MINUS,	INTAREG,
	RWD,	TLONG|TULONG,
	SICON,	TINT|TLONG|TULONG,
		0,	RESC1,
		"/*121*/	subl	D1,DR\n",

ASG MINUS,	INTAREG,
	RWD,	TLONG|TULONG,
	AWD,	TLONG|TULONG,
		0,	RLEFT,
		"/*122*/	subl	DL,DR\n",

/*
	on the next three productions might
	want to have the left side be a register,
	do op into the reg and reclaim the reg.
	(only two instr)
	change made 9/23/81 ERR
 */
ASG OR, 	INTAREG,
	RWD,	TLONG|TULONG,
	AWD|RWD,	TLONG|TULONG,
		0,	RLEFT,
		"/*125*/	or	AL,AR\
			\n	or	UL,UR\n",

ASG AND,	INTAREG,
	RWD,	TLONG|TULONG,
	AWD|RWD,	TLONG|TULONG,
		0,	RLEFT,
		"/*126*/	and	AL,AR\
			\n	and	UL,UR\n",

	/* table entries for ^ which correspond to the usual way of doing busingess
		(rhs in a temp register */

ASG ER,	INTAREG,
	RWD,	TLONG|TULONG,
	AWD|RWD,	TLONG|TULONG,
		0,	RLEFT,
		"/*128*/	xor	AL,AR\n	xor	UL,UR\n",

ASG OPFLOAT,	INTAREG,
	RWD,	TDOUBLE|TFLOAT,
	RWD,	TFIT,
		0,	RLEFT,
		"/*134*/	OF#d	QL,QR#)\n",

#ifdef shit
ASG OPFLOAT,	FORCC,
	RWD,	TDOUBLE|TFLOAT,
	RWD,	TFIT,
		0,	RESCC,
		"/*143*/	OF#d	QL,QR#)\n	ldk	V1,$0\
			\n	fitod	Q1,V1\n	fcp#d	QL,Q1#)\n",
#endif

UNARY CALL,	INTAREG,
	RWD,	TANY,
	SANY,	TINT|TUNSIGNED|TPOINT|TCHAR|TUCHAR,
		NAREG|NASL,	RESC1,
		"/*145*/	call	*AL\n",

UNARY CALL,	INTAREG,
	RWD,	TANY,
	SANY,	TLONG|TULONG,
		NAREG|NASL,	RESC1,
		"/*146*/	call	*AL\n",

UNARY CALL,	INTAREG,
	SOREG,	TANY,
	SANY,	TANY,
		NAREG|NASL,	RESC1, /* should be register 7 */
		"/*147*/	ld	A1,AL\n	call	*A1\n",

UNARY CALL,	INTAREG,
	SCON,	TANY,
	SANY,	TANY,
		NAREG|NASL,	RESC1, /* should be register 7 */
		"/*148*/#$	call	AL#)\n",

UNARY CALL,	INTAREG,
	SNAME,	TANY,
	SANY,	TANY,
		NAREG|NASL,	RESC1, /* should be register 7 */
		"/*149*/	ld	A1,AL\n	call	*A1\n",

UNARY CALL,	INTAREG,
	AWD,	TANY,
	SANY,	TDOUBLE|TFLOAT,
		NAREG,	RESC1,
		"/*150*/#$	call	AL#)\n",

SCONV,	INTAREG,
	AWD|SAREG,	TCHAR|TUCHAR,
	SANY,	TCHAR|TUCHAR,
		0,	RLEFT,
		"/*151*/\n",

SCONV,	INTAREG,
	AWD|SAREG,	TINT|TUNSIGNED|TPOINT,
	SANY,	TINT|TUNSIGNED|TPOINT,
		0,	RLEFT,
		"/*152*/\n",

SCONV,	INTAREG,
	AWD|RWD,	TLONG|TULONG,
	SANY,	TLONG|TULONG,
		0,	RLEFT,
		"/*153*/\n",

SCONV,	INTAREG,
	AWD,	TINT|TUNSIGNED|TPOINT|TLONG|TULONG,
	SANY,	TCHAR|TUCHAR|TINT|TPOINT|TUNSIGNED,
		0,	RLEFT,
		"/*155*/ZT\n",

SCONV,	INTAREG,
	STAREG,	TCHAR,
	SANY,	TINT|TPOINT|TUNSIGNED,
		0,	RLEFT,
		"/*155+*/	extsb	A1\n",

SCONV,	INTAREG,
	RWD,	TLONG|TULONG,
	SANY,	TINT|TPOINT|TUNSIGNED,
		0,	RLEFT,
		"/*155++*/ZT\n",

SCONV,	INTAREG,
	AWD,	TCHAR,
	SANY,	TINT|TPOINT|TUNSIGNED,
		NAREG|NASL,	RESC1,
		"/*156-*/#L	ldb	A1,AL#)\n	extsb	A1\n",

SCONV,	INTAREG,
	STAREG,	TUCHAR,
	SANY,	TINT|TPOINT|TUNSIGNED,
		0,	RLEFT,
		"/*156*/#H	ldb	A1,$0#)\n",

SCONV,	INTAREG,
	AWD,	TUCHAR,
	SANY,	TINT|TPOINT|TUNSIGNED,
		NAREG|NASL,	RESC1,
		"/*156+*/#L	ldb	A1,AL#)\n#H	ldb	A1,$0#)\n",

SCONV,	INTAREG,
	AWD,	TUCHAR,
	SANY,	TLONG|TULONG,
		NAREG|NASL,	RESC1,
		"/*157*/#L	ldb	U1,AL#)\n#H	ldb	U1,$0#)\
			\n	ldk	A1,$0\n",

SCONV,	INTAREG,
	AWD,	TCHAR,
	SANY,	TLONG|TULONG,
		NAREG|NASL,	RESC1,
		"/*157+*/#L	ldb	U1,AL#)\n	extsb	U1\
			\n	exts	D1\n",

SCONV,	INTAREG,
	SAREG|AWD,	TINT,
	SANY,	TLONG|TULONG,
		NAREG|NASL,	RESC1,
		"/*158*/	ld	U1,AL\n	exts	D1\n",

SCONV,	INTAREG,
	AWD,	TUNSIGNED|TPOINT,
	SANY,	TLONG|TULONG,
		NAREG|NASL,	RESC1,
		"/*159*/	ld	U1,AL\n	ldk	A1,$0\n",

SCONV,	INTAREG,
	RWD,	TDOUBLE,
	SANY,	TFLOAT,
		0,	RLEFT,
		"/*160-*/	fdtof	EL,QL\n",

SCONV,	INTAREG,
	RWD,	TFLOAT,
	SANY,	TDOUBLE,
		0,	RLEFT,
		"/*160--*/	fftod	QL,EL\n",

SCONV,	INTAREG,
	RWD,	TDOUBLE|TFLOAT,
	SANY,	TINT|TUNSIGNED|TPOINT|TCHAR|TUCHAR,
		0,	RLEFT|RESCLIQ,
		"/*160*/	f#Dtoi	VL,QL#)\n",

SCONV,	INTAREG,
	RWD,	TDOUBLE|TFLOAT,
	SANY,	TLONG|TULONG,
		0,	RLEFT|RESCLLQ,
		"/*162*/	f#Dtol	EL,QL#)\n",

SCONV,	FORARG,
	RWD,	TDOUBLE|TFLOAT,
	SANY,	TLONG|TULONG,
		0,	RNULL,
		"/*164*/	f#Dtol	EL,QL#)\n	ldl	DL,EL\
			\n	pushl	*r15,DL\nZ-Z-",

SCONV,	INTAREG,
	RWD,	TFLOAT|TDOUBLE,
	SANY,	TFIT,
		0,	RLEFT,
		"/*166*/\n",

SCONV,	INTAREG,
	AWD|RWD,	TLONG,
	SANY,	TDOUBLE|TFLOAT,
		NAREG|NASL,	RESC1,
		"/*169*/	ldl	E1,DL\n	flto#D	Q1,E1#)\n",

SCONV,	INTAREG,
	SAREG|AWD,	TINT,
	SANY,	TDOUBLE|TFLOAT,
		NAREG|NASL,	RESC1,
		"/*171*/	ld	V1,AL\n	fito#D	Q1,V1#)\n",

SCONV,	INTAREG,
	RWD|AWD,	TCHAR,
	SANY,	TDOUBLE|TFLOAT,
		NAREG|NASL,	RESC1,
		"/*172*/#L	ldb	V1,AL#)\n	extsb	V1\
			\n	fito#D	Q1,V1#)\n",

SCONV,	INTAREG,
	RWD|AWD,	TUCHAR,
	SANY,	TDOUBLE|TFLOAT,
		NAREG|NASL,	RESC1,
		"/*172+*/#L	ldb	V1,AL#)\n#H	ldb	V1,$0#)\
			\n	fito#D	Q1,V1#)\n",

SCONV,	INTAREG,
	AWD|RWD,	TULONG,
	SANY,	TDOUBLE|TFLOAT,
		NAREG|NASL,	RESC1,
		"/*173*/	ldl	E1,DL\n	futo#D	Q1,E1#)\n",

SCONV,	INTAREG,
	RWD,	TUNSIGNED|TPOINT,
	SANY,	TDOUBLE|TFLOAT,
		NAREG|NASL,	RESC1,
		"/*175*/	ldk	G1,$0\n	ld	V1,AL\
			\n	flto#D	Q1,E1#)\n",

PCONV,	INTAREG,
	AWD,	TCHAR|TUCHAR,
	SANY,	TPOINT,
		NAREG|NASL,	RESC1,
		"/*177*/#L	ldb	A1,AL#)\n	extsb	A1\n",

PCONV,	INTAREG,
	AWD|RWD,	TLONG|TULONG,
	SANY,	TPOINT,
		0,	RLEFT,
		"/*178*/ZT\n",

STARG,	FORARG,
	SNAME|SOREG,	TANY,
	SANY,	TANY,
		2*NAREG,	RNULL,
		"/*179*/	ld	U1,$ZX\n#A	lda	A1,ZW-2+AL#)\
			\nZY\
			\n	lddr	*r15,*A1,U1\
			\n	inc	r15,$2\n",


STASG,	INTAREG,
	SNAME|SOREG,	TANY,
	RWD,	TANY,
		2*NAREG,	RRIGHT,
		"/*180*/	ld	U1,$ZX\n#A	lda	A1,AL#)\
			\n	ldir	*A1,*AR,U1\n	sub	AR,$ZW\n",

INIT,	FOREFF,
	SCON,	TANY,
	SANY,	TINT|TUNSIGNED|TPOINT,
		0,	RNOP,
		"/*181*/	.word	CL\n",

INIT,	FOREFF,
	SCON,	TANY,
	SANY,	TLONG|TULONG,
		0,	RNOP,
		"/*182*/	.long	CL\n",

INIT,	FOREFF,
	SCON,	TANY,
	SANY,	TCHAR|TUCHAR,
		0,	RNOP,
		"/*183*/	.byte	CL\n",

	/* for the use of fortran only */

GOTO,	FOREFF,
	SCON,	TANY,
	SANY,	TANY,
		0,	RNOP,
		"/*184*/	jpr	CL\n",

GOTO,	FOREFF,
	SNAME,	TLONG|TULONG,
	SANY,	TANY,
		0,	RNOP,
		"/*185*/	jpr	UL\n",

GOTO,	FOREFF,
	SNAME,	TINT|TUNSIGNED|TCHAR|TUCHAR|TPOINT,
	SANY,	TANY,
		0,	RNOP,
		"/*186*/	jpr	AL\n",

	/* Default actions for hard trees ... */

# define DF(x) FORREW,SANY,TANY,SANY,TANY,REWRITE,x,""

UNARY MUL, DF( UNARY MUL ),

INCR, DF(INCR),

DECR, DF(INCR),

ASSIGN, DF(ASSIGN),

STASG, DF(STASG),

OPLEAF, DF(NAME),

OPLOG,	FORCC,
	SANY,	TANY,
	SANY,	TANY,
		REWRITE,	BITYPE,
		"",

OPLOG,	DF(NOT),

COMOP, DF(COMOP),

INIT, DF(INIT),

OPUNARY, DF(UNARY MINUS),


ASG OPANY, DF(ASG PLUS),

OPANY, DF(BITYPE),

FREE,	FREE,	FREE,	FREE,	FREE,	FREE,	FREE,	FREE,	"help; I'm in trouble\n" };
